proyek/buah/urls.py
from django.urls import path

from .views import tambah_buah, list_buah, detail_buah, update_buah, delete_buah

app_name = "buah"

urlpatterns = [
    path('tambah/', tambah_buah, name="tambah_buah"),
    path('detail/<pk>/', detail_buah, name="detail_buah"),
    path('update/<pk>/', update_buah, name="update_buah"),
    path('delete/<pk>/', delete_buah, name="delete_buah"),
    path('', list_buah, name="list_buah"),
]

proyek/proyek/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('buah.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyek/buah/models.py
from django.db import models

# Create your models here.
class TabelBuah(models.Model):
    nama = models.CharField(max_length=50)
    gambar = models.ImageField(upload_to='buah/')
    keterangan = models.TextField()

    class Meta:
        ordering = ['-id']
    
    def __str__(self):
        return self.nama

proyek/buah/forms.py
from django import forms

from .models import TabelBuah

class TabelBuahForm(forms.ModelForm):
    class Meta:
        model = TabelBuah
        fields = '__all__'

proyek/buah/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse

from .models import TabelBuah
from .forms import TabelBuahForm

# Create your views here.

# create views
def tambah_buah(request):
    if request.method == 'POST':
        form = TabelBuahForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    return render(request, 'tambah_buah.html', {'form': TabelBuahForm})

# Retrieve
# 1. List View
def list_buah(request):
    context = {}
    context['buah'] = TabelBuah.objects.all()
    return render(request, 'list_buah.html', context)

# 2. Detail View
def detail_buah(request, pk):
    context = {
        'data': TabelBuah.objects.get(id = pk)
    }
    return render(request, 'detail_buah.html', context)

# Update View
def update_buah(request, pk):
    context = {}

    obj = get_object_or_404(TabelBuah, id = pk)
    form = TabelBuahForm(request.POST or None, request.FILES or None, instance = obj)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('buah:detail_buah', args=(obj.id,)))
    
    context['form'] = form
    return render(request, 'tambah_buah.html', context)

# Delete View
def delete_buah(request, pk):
    context = {}

    obj = get_object_or_404(TabelBuah, id = pk)
    if request.method == "POST":
        obj.delete()
        return HttpResponseRedirect("/")
    return render(request, 'delete_buah.html', context)

proyek/templates/delete_buah.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>Apakah Anda yakin akan menghapus {{ data }}</p>
        <input type="submit" value="Hapus"/> | <a href="/">Batal</a>
    </form>
</body>
</html>

proyek/templates/detail_buah.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="main">
        {{ data.nama }} <br>
        {% if data.gambar %}
        <img src="{{ data.gambar.url }}" alt="{{ data.nama }}"/>
        {% endif %}
        {{ data.keterangan }}

        <p><strong>Action:</strong> | <a href="{% url 'buah:update_buah' data.id %}">Update Buah</a> | 
        <a href="{% url 'buah:delete_buah' data.id %}">Hapus</a>
        </p>

    </div>
</body>
</html>

proyek/templates/list_buah.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List Buah</title>
</head>
<body>
    <div class="main">
        <a href="{% url 'buah:tambah_buah' %}">Tambah Buah</a> <br>
        {% for data in buah %}
        <a href="{% url 'buah:detail_buah' data.id %}">{{ data.nama }}</a> <br>
        {% endfor %}
    </div>
</body>
</html>

proyek/templates/tambah_buah.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tambah Buah</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Simpan">
    </form>
</body>
</html>